### PR TITLE
Apple Page Clone

### PR DESCRIPTION
**Pull request by Laguna1**
A clone of the old Apple page,
My project was done using background images and gradients.
Please review this code.

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Oksana!  
### Your project looks :+1: good!
Here are required changes, before this project can be approved:
* [x] Navigation bar should use CSS [`background -> gradient`](https://www.w3schools.com/cssref/css3_pr_background.asp) for background ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/building_with_backgrounds_and_gradients/navigation_requirement.png) from [Odin](https://www.theodinproject.com/courses/html5-and-css3/lessons/building-with-backgrounds-and-gradients)) Right now you are using image, that needs to be corrected.
* [x] Font size of navbar buttons is too small, it doesn't look like original. Please make it a bit bigger.
* [x] `image-bar` div should contain four elements which are links (to another articles or `#`) ([link to page](https://web.archive.org/web/20140301004610/http://www.apple.com/))

[OPTONAL]
* It's a good practice to use the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) for the dominant content of the `<body>` of a document

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by Laguna1** [comment]
As always, thanks for your helpful comments, everything will be fixed.

пн, 3 февр. 2020 г. в 22:59, Olga Pelts <notifications@github.com>:

**Comment by Laguna1** [comment]
I made some changes to this project taking into account the comments made by TSE.
I replaced the background-image of the <nav> with a linear gradient,
changed the font-size of the navbar elements
and added links to each elements <div class="image-bar">.
Please check my project, I hope that this time everything is already fine here.
Thanks!

**Review by mosesogwo — APPROVED** [review]
### :trophy:Congratulations. Your project is approved!

Before you merge to master, update your README with the following changes:

1. Remove this extra-link: 
image

2. Correct this spelling
image

**Good luck in your next project:smile:**

### Status: Approved.

**Pull request merged**
